import { GetStaticProps } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { fetchApplicants } from './api/applicants'

export default function Home({ applicants }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {applicants.map((m, i) => (
        <div id={i}>
          <a href={`/applicant/${i}`}>{m.name.first}</a>
        </div>
      ))}
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const applicants = await fetchApplicants();
  return {
    props: {
      applicants: applicants.results
    }
  }
}