import { GetServerSideProps, GetStaticProps } from 'next'
import Head from 'next/head'
import { environment } from '../config'
import styles from '../styles/Home.module.css'

export default function Home({ applicants }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {applicants.map(m => (
        <div>{m.name.first}</div>
      ))}
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch(`${environment}/api/applicants`);
  const applicants = await res.json();
  return {
    props: {
      applicants: applicants
    }
  }
}