import { GetStaticProps } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { fetchApplicants } from './api/applicants'
import React, { useState, useEffect } from 'react'
import Carousel from '../components/Carousel'

export default function Home({ applicants }) {
  const CAROUSEL_TIMEOUT = 5000;
  const [current, setCurrent] = useState(0);

  useEffect(() => {

    const next = (current + 1) % applicants.length;

    const id = setTimeout(() => setCurrent(next), CAROUSEL_TIMEOUT);

    return () => clearTimeout(id);

  }, [current]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <Carousel applicants={applicants} />
      </div>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const applicants = await fetchApplicants();
  return {
    props: {
      applicants: applicants.results
    }
  }
}